### ISSUE TITLE
AssertionError: litgen/code_to_adapted_unit.py", line 29, in code_to_adapted_unit_in_context

### ISSUE THREAD

**Issue by pixtop** [pthom/litgen#8]
Hello, first of all, thank you for your effort!

I'm testing your tool against a C++ API written by DekTec.

They provide an already compiled file (.o) with a header file to use their API (I have attached the files).

I have tried to run your autogenerated binding tool which comes from your template project, but it raises an exception.
See the traceback below:
> Traceback (most recent call last):
  File "/opt/projects/litgen_template/tools/autogenerate_bindings.py", line 105, in <module>
    autogenerate()
  File "/opt/projects/litgen_template/tools/autogenerate_bindings.py", line 96, in autogenerate
    litgen.write_generated_code_for_files(
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/litgen/litgen_generator.py", line 227, in write_generated_code_for_files
    generator.process_cpp_file(cpp_header)
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/litgen/litgen_generator.py", line 83, in process_cpp_file
    self.process_cpp_code(code, filename)
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/litgen/litgen_generator.py", line 181, in process_cpp_code
    adapted_unit = code_to_adapted_unit_in_context(self.lg_context, code, filename)
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/litgen/code_to_adapted_unit.py", line 29, in code_to_adapted_unit_in_context
    cpp_unit = srcmlcpp.code_to_cpp_unit(lg_context.options.srcmlcpp_options, code, filename)
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/srcmlcpp/srcmlcpp_main.py", line 123, in code_to_cpp_unit
    cpp_unit = _code_to_cpp_unit_impl(options, code, filename, fill_known_cache)
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/srcmlcpp/srcmlcpp_main.py", line 104, in _code_to_cpp_unit_impl
    cpp_unit = cpp_types_parse.parse_unit(options, xml_wrapper)
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/srcmlcpp/internal/cpp_types_parse.py", line 920, in parse_unit
    fill_block(options, element, cpp_unit)
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/srcmlcpp/internal/cpp_types_parse.py", line 886, in fill_block
    block_children.append(parse_namespace(options, child_c, inout_block_content))
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/srcmlcpp/internal/cpp_types_parse.py", line 977, in parse_namespace
    result.block = parse_block(options, child, element_c)
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/srcmlcpp/internal/cpp_types_parse.py", line 751, in parse_block
    fill_block(options, element, cpp_block)
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/srcmlcpp/internal/cpp_types_parse.py", line 884, in fill_block
    block_children.append(parse_struct_or_class(options, child_c, inout_block_content))
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/srcmlcpp/internal/cpp_types_parse.py", line 706, in parse_struct_or_class
    result.block = parse_block(options, child, result)
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/srcmlcpp/internal/cpp_types_parse.py", line 751, in parse_block
    fill_block(options, element, cpp_block)
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/srcmlcpp/internal/cpp_types_parse.py", line 905, in fill_block
    block_children.append(parse_public_protected_private(options, child_c, inout_block_content))
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/srcmlcpp/internal/cpp_types_parse.py", line 739, in parse_public_protected_private
    fill_block(options, element_c, block_content)
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/srcmlcpp/internal/cpp_types_parse.py", line 854, in fill_block
    fixed_ctor = fix_brace_init_default_value.change_macro_to_constructor(options, macro_maybe_constructor)
  File "/opt/projects/litgen_template/.venv/lib/python3.10/site-packages/srcmlcpp/internal/fix_brace_init_default_value.py", line 181, in change_macro_to_constructor
    assert len(fixed_functions) == 1
AssertionError

Firstly, do you think this kind of API is compatible with your tool?
Secondly, do you have any idea about the issue?

[DTAPI.zip](https://github.com/pthom/litgen/files/14948156/DTAPI.zip)

**Comment by pthom** [comment]
Please try to provide me with a minimal reproducible example that is shorter than this full zip file.

**Comment by pthom** [comment]
Hi, this API seems ok for litgen. I pushed a fix
